name: stack_chart
description: A flutter package for customized stacked chart use within your applications.

version: 1.0.0
# repository: https://github.com/my_org/my_repo
# author: Macincode Technologies

homepage: https://github.com/zeroappz/stack_chart
environment:
  sdk: '>=2.19.6 <3.0.0'

# dependencies:
#   path: ^1.8.0
dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
