name: stack_chart
description: A flutter package for customized stacked chart use within your applications.

version: 1.0.1+2
repository: https://github.com/zeroappz/stack_chart

homepage: https://www.macincode.com
environment:
  sdk: ">=2.19.6 <3.1.1"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
